import {
  Box,
  Flex,
  Heading,
  Image,
  Table,
  TableContainer,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import React from "react";
import Header from "./components/Header";
import LeftSideBar from "./components/LeftSideBar";

const Users = () => {
  const date = new Date();
  const d = `${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`;
  return (
    <Box>
      <Header />
      <LeftSideBar />
      <Box pl={250} pt={75}>
        <Heading fontSize={50}>Users</Heading>
        <TableContainer pt={5}>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>PICTURE</Th>
                <Th>USERNAME</Th>
                <Th>EMAIL</Th>
                <Th>PASSWORD</Th>
                <Th>LAST LOGIN</Th>
              </Tr>
            </Thead>
            <Tbody>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
              <Tr>
                <Td>1</Td>
                <Td>
                  <Flex>
                    <Image
                      width={50}
                      height={50}
                      objectFit={"cover"}
                      borderRadius={40}
                      src="https://img.freepik.com/free-photo/handsome-man-smiling-happy-face-portrait-close-up_53876-139608.jpg?w=740&t=st=1707313441~exp=1707314041~hmac=f4fdede70854ae687e6b6ac43bf6c3c91664f4bc8d35d4ff2ac5cc20adfbe1cd"
                    />
                  </Flex>
                </Td>
                <Td>areegbedavid</Td>
                <Td>areegbedavid@gmail.com</Td>
                <Td>**********************</Td>
                <Td>{d}</Td>
              </Tr>
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </Box>
  );
};

export default Users;
